#!/bin/bash
siteName=$1
archive=$siteName.tar.gz
deployLocation=/www/sites

if [ $siteName ]; then
	if [ -d $siteName ]; then
		echo "Deploying this site: $siteName"
		echo "Creating archive..."
		tar -czf $archive $siteName
		echo "Moving archive"
		mv $archive  $deployLocation
	else
		echo "No such site!"
	fi
else
	echo "No site specified."
fi
